2.Write a note on Finally keyword and explain it with the help of program.

The finally keyword is used in try...except blocks. It defines a block of code to run when the try...except...else block is final.
The finally block will be executed no matter if the try block raises an error or not.
This can be useful to close objects and clean up resources.

Ex:-
#The finally block will always be executed, no matter if the try block raises an error or not:

def checkp(x):
     try:    
         if x > 1:
            print("x is greater than 1")
     except:
        print("Something went wrong")

     finally:
        print("The try...except block is finished")


# If X = 3
checkp(3)


Output:
x is greater than 1
The try...except block is finished

