WAP to multiple except in one try with proper comments and notes

We can specify which exception except block should catch or handle. 
A try block can be followed by multiple numbers of except blocks to handle the different exceptions. 
But only one exception will be executed when an exception occurs.

Example:
In this example, we will ask the user for the denominator value. If the user enters a number, the program will evaluate and produce the result.
If the user enters a non-numeric value then, the try block will throw a ValueError exception, and we can catch that using a first catch block ‘except ValueError’ by printing the message ‘Entered value is wrong’.
And suppose the user enters the denominator as zero. In that case, the try block will throw a ZeroDivisionError, and we can catch that using a second catch block by printing the message ‘Can’t divide by zero’.

try:
    a = int(input("Enter value of a: "))
    b = int(input("Enter value of b: "))
    c = a/b
    print("a/b = ", c)
except ValueError:
    print("Invalid Input, Value must be Integer")
    
except ZeroDivisionError:
    print("Zero Division Error")

Output 1:
Enter value of a: five
Invalid Input, Value must be Integer

Output 2:
Enter value of a:10
Enter value of b:0
Zero Division Error

Output 3:
Enter value of a:10
Enter value of b:2
The answer of a divide by b: 5.0

